name: Docker build and push

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # DO_PUSH - true to push to the HPE_DEPLOY_REPO, false to not push
  DO_PUSH: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lowercase repository name for docker build
      id: lowercase-repository-name
      run: |
        echo "HPE_BUILD_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "HPE_DEPLOY_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: set TAG for main/master
      if: ${{ github.event.repository.default_branch == 'main' || github.event.repository.default_branch == 'master' }}
      run: |
        echo "TAG=${{ github.sha }}" >> ${GITHUB_ENV}
        echo "LATESTTAG=latest" >> ${GITHUB_ENV}

    - name: set TAG for all other branches
      if: ${{ github.event.repository.default_branch != 'main' && github.event.repository.default_branch != 'master' }}
      run: |
        echo "TAG=dev-${{ github.sha }}" >> ${GITHUB_ENV}
        echo "LATESTTAG=dev-latest" >> ${GITHUB_ENV}

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the final Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ env.HPE_BUILD_REPO }}:${{ env.TAG }}

    - name: Peek at the docker images
      run: docker images

    - name: Tag the build
      run: docker tag docker.io/${HPE_BUILD_REPO}:${TAG} ghcr.io/${HPE_DEPLOY_REPO}:${TAG}

    - name: Tag the build as latest
      run: docker tag ${HPE_BUILD_REPO}:${TAG} ghcr.io/${HPE_DEPLOY_REPO}:${LATESTTAG}

    - name: Push the tagged build
      if: ${{ env.DO_PUSH == 'true' }}
      run: docker push ghcr.io/${HPE_DEPLOY_REPO}:${TAG}

    - name: Push the build tagged as latest
      if: ${{ env.DO_PUSH == 'true' }}
      run: docker push ghcr.io/${HPE_DEPLOY_REPO}:${LATESTTAG}
